CREATE OR REPLACE FUNCTION replace_organization_form AS (payer_of_the_railway_tariff) ->
multiIf(
    payer_of_the_railway_tariff LIKE '%ИНДИВИДУАЛЬНЫЙ ПРЕДПРИНИМАТЕЛЬ%',
    replaceAll(payer_of_the_railway_tariff,
    'ИНДИВИДУАЛЬНЫЙ ПРЕДПРИНИМАТЕЛЬ',
    'ИП '),
    payer_of_the_railway_tariff LIKE '%ИП%',
    replaceAll(payer_of_the_railway_tariff,
    'ИНДИВИДУАЛЬНЫЙ ПРЕДПРИНИМАТЕЛЬ',
    'ИП '),
    payer_of_the_railway_tariff LIKE '%ОБОСОБЛЕННОЕ ПОДРАЗДЕЛЕНИЕ ОБЩЕСТВА С ОГРАНИЧЕННОЙ ОТВЕТСТВЕННОСТЬЮ%',
    replaceAll(payer_of_the_railway_tariff,
    'ОБОСОБЛЕННОЕ ПОДРАЗДЕЛЕНИЕ ОБЩЕСТВА С ОГРАНИЧЕННОЙ ОТВЕТСТВЕННОСТЬЮ',
    'ОП ООО '),
    payer_of_the_railway_tariff LIKE '%ОБЩЕСТВО С ОГРАНИЧЕННОЙ ОТВЕТСТВЕННОСТЬЮ%',
    replaceAll(payer_of_the_railway_tariff,
    'ОБЩЕСТВО С ОГРАНИЧЕННОЙ ОТВЕТСТВЕННОСТЬЮ',
    'ООО '),
    payer_of_the_railway_tariff LIKE '%ОБШЕСТВО С ОГРАНИЧЕННОЙ ОТВЕТСТВЕННОСТЬЮ%',
    replaceAll(payer_of_the_railway_tariff,
    'ОБШЕСТВО С ОГРАНИЧЕННОЙ ОТВЕТСТВЕННОСТЬЮ',
    'ООО '),
    payer_of_the_railway_tariff LIKE '%ОБЩЕСТВО С ОГАНИЧЕННОЙ ОТВЕТСТВЕННОСТЬЮ%',
    replaceAll(payer_of_the_railway_tariff,
    'ОБЩЕСТВО С ОГАНИЧЕННОЙ ОТВЕТСТВЕННОСТЬЮ',
    'ООО '),
    payer_of_the_railway_tariff LIKE '%ОБЩЕСТВО С ОГРАНИЦЕННОЙ ОТВЕТСТВЕННОСТЬЮ%',
    replaceAll(payer_of_the_railway_tariff,
    'ОБЩЕСТВО С ОГРАНИЦЕННОЙ ОТВЕТСТВЕННОСТЬЮ',
    'ООО '),
    payer_of_the_railway_tariff LIKE '%ОБЩЕСТВО С ОГРАНИЧЕНННОЙ ОТВЕТСТВЕННОСТЬЮ%',
    replaceAll(payer_of_the_railway_tariff,
    'ОБЩЕСТВО С ОГРАНИЧЕНННОЙ ОТВЕТСТВЕННОСТЬЮ',
    'ООО '),
    payer_of_the_railway_tariff LIKE '%ОБЩЕСТВО С ОГРАНИЧЕННОЙ ОТВЕНТСТВЕННОСТЬЮ%',
    replaceAll(payer_of_the_railway_tariff,
    'ОБЩЕСТВО С ОГРАНИЧЕННОЙ ОТВЕНТСТВЕННОСТЬЮ',
    'ООО '),
    payer_of_the_railway_tariff LIKE '%ОБЩЕСТВО С ОГРАНИЧЕННОЙ ОТВЕСТВЕННОСТЬЮ%',
    replaceAll(payer_of_the_railway_tariff,
    'ОБЩЕСТВО С ОГРАНИЧЕННОЙ ОТВЕСТВЕННОСТЬЮ',
    'ООО '),
    payer_of_the_railway_tariff LIKE '%ОБЩЕСТВО С ОГРАНИЧЕННОЙ ОТВЕТВЕННОСТЬЮ%',
    replaceAll(payer_of_the_railway_tariff,
    'ОБЩЕСТВО С ОГРАНИЧЕННОЙ ОТВЕТВЕННОСТЬЮ',
    'ООО '),
    payer_of_the_railway_tariff LIKE '%ОБЩЕСТВО С ОГРАНИЧЕННОЙ ОТВЕТСВЕННОСТЬЮ%',
    replaceAll(payer_of_the_railway_tariff,
    'ОБЩЕСТВО С ОГРАНИЧЕННОЙ ОТВЕТСВЕННОСТЬЮ',
    'ООО '),
    payer_of_the_railway_tariff LIKE '%ОБЩЕСТВО С ОГРАНИЧЕННОЙ ОТВЕТСТВЕНННОСТЬЮ%',
    replaceAll(payer_of_the_railway_tariff,
    'ОБЩЕСТВО С ОГРАНИЧЕННОЙ ОТВЕТСТВЕНННОСТЬЮ',
    'ООО '),
    payer_of_the_railway_tariff LIKE '%ОБЩЕСТВО С ОГРАНИЧЕННОЙ ОТВЕТСТСЕННОСТЬЮ%',
    replaceAll(payer_of_the_railway_tariff,
    'ОБЩЕСТВО С ОГРАНИЧЕННОЙ ОТВЕТСТСЕННОСТЬЮ',
    'ООО '),
    payer_of_the_railway_tariff LIKE '%ОБЩЕСТВО С ОГРАНИЧЕННОЙ ОТВТСТВЕННОСТЬЮ%',
    replaceAll(payer_of_the_railway_tariff,
    'ОБЩЕСТВО С ОГРАНИЧЕННОЙ ОТВТСТВЕННОСТЬЮ',
    'ООО '),
    payer_of_the_railway_tariff LIKE '%ОБЩЕСТВО С ОГРАНИЧЕННОЙ ТВЕТСТВЕННОСТЬЮ%',
    replaceAll(payer_of_the_railway_tariff,
    'ОБЩЕСТВО С ОГРАНИЧЕННОЙ ТВЕТСТВЕННОСТЬЮ',
    'ООО '),
    payer_of_the_railway_tariff LIKE '%ОБЩЕСТВО С ОГРАНИЧЕННОЙОТВЕТСТВЕННОСТЬЮ%',
    replaceAll(payer_of_the_railway_tariff,
    'ОБЩЕСТВО С ОГРАНИЧЕННОЙОТВЕТСТВЕННОСТЬЮ',
    'ООО '),
    payer_of_the_railway_tariff LIKE '%ОБЩЕСТВО С ОГРАНИЧЕНОЙ ОТВЕТСТВЕННОСТЬЮ%',
    replaceAll(payer_of_the_railway_tariff,
    'ОБЩЕСТВО С ОГРАНИЧЕНОЙ ОТВЕТСТВЕННОСТЬЮ',
    'ООО '),
    payer_of_the_railway_tariff LIKE '%ОБЩЕСТВО С ОЛГРАНИЧЕННОЙ ОТВЕТСТВЕННОСТЬЮ%',
    replaceAll(payer_of_the_railway_tariff,
    'ОБЩЕСТВО С ОЛГРАНИЧЕННОЙ ОТВЕТСТВЕННОСТЬЮ',
    'ООО '),
    payer_of_the_railway_tariff LIKE '%ОБЩЕСТВО С ОРГАНИЧЕННОЙ ОТВЕТСТВЕННОСТЬЮ%',
    replaceAll(payer_of_the_railway_tariff,
    'ОБЩЕСТВО С ОРГАНИЧЕННОЙ ОТВЕТСТВЕННОСТЬЮ',
    'ООО '),
    payer_of_the_railway_tariff LIKE '%ОБЩЕСТВА С ОГРАНИЧЕННОЙ ОТВЕТСТВЕННОСТЬЮ%',
    replaceAll(payer_of_the_railway_tariff,
    'ОБЩЕСТВА С ОГРАНИЧЕННОЙ ОТВЕТСТВЕННОСТЬЮ',
    'ООО '),
    payer_of_the_railway_tariff LIKE '%ОБЩЕСТВО С ОГРАНИЧЕННОЙ ОТВЕТСТВЕННОСТЬ%',
    replaceAll(payer_of_the_railway_tariff,
    'ОБЩЕСТВО С ОГРАНИЧЕННОЙ ОТВЕТСТВЕННОСТЬ',
    'ООО '),
    payer_of_the_railway_tariff LIKE '%ОБЩЕСТВО С ОГРАНИЧННОЙ ОТВЕТСТВЕННОСТЬЮ%',
    replaceAll(payer_of_the_railway_tariff,
    'ОБЩЕСТВО С ОГРАНИЧННОЙ ОТВЕТСТВЕННОСТЬЮ',
    'ООО '),
    payer_of_the_railway_tariff LIKE '%ОБЩЕСТВО С ОГРАНИЧЕННОЙ ОТВЕТСТСВЕННОСТЬЮ%',
    replaceAll(payer_of_the_railway_tariff,
    'ОБЩЕСТВО С ОГРАНИЧЕННОЙ ОТВЕТСТСВЕННОСТЬЮ',
    'ООО '),
    payer_of_the_railway_tariff LIKE '%ТОВАРИЩЕСТВО С ОГРАНИЧЕННОЙ ОТВЕТСТВЕННОСТЬЮ%',
    replaceAll(payer_of_the_railway_tariff,
    'ТОВАРИЩЕСТВО С ОГРАНИЧЕННОЙ ОТВЕТСТВЕННОСТЬЮ',
    'ООО '),
    payer_of_the_railway_tariff LIKE '%(ОБЩЕСТВО С ОГРАНИЧЕННОЙ%',
    replaceAll(payer_of_the_railway_tariff,
    '(ОБЩЕСТВО С ОГРАНИЧЕННОЙ',
    'ООО '),
    payer_of_the_railway_tariff LIKE '%НЕПУБЛИЧНОЕ АКЦИОНЕРНОЕ ОБЩЕСТВО%',
    replaceAll(payer_of_the_railway_tariff,
    'НЕПУБЛИЧНОЕ АКЦИОНЕРНОЕ ОБЩЕСТВО',
    'НАО '),
    payer_of_the_railway_tariff LIKE '%ПУБЛИЧНОЕ АКЦИОНЕРНОЕ ОБЩЕСТВО ЦЕНТР ПО ПЕРЕВОЗКЕ ГРУЗОВ В КОНТЕЙНЕРА%',
    replaceAll(payer_of_the_railway_tariff,
    'ПУБЛИЧНОЕ АКЦИОНЕРНОЕ ОБЩЕСТВО ЦЕНТР ПО ПЕРЕВОЗКЕ ГРУЗОВ В КОНТЕЙНЕРА',
    'ПАО ТРАНСКОНТЕЙНЕР '),
    payer_of_the_railway_tariff LIKE '%ПУБЛИЧНОЕ АКЦИОНЕРНОЕ ОБЩЕСТВО%',
    replaceAll(payer_of_the_railway_tariff,
    'ПУБЛИЧНОЕ АКЦИОНЕРНОЕ ОБЩЕСТВО',
    'ПАО '),
    payer_of_the_railway_tariff LIKE '%ПУБЛИЧНОГО АКЦИОНЕРНОГО ОБЩЕСТВА%',
    replaceAll(payer_of_the_railway_tariff,
    'ПУБЛИЧНОГО АКЦИОНЕРНОГО ОБЩЕСТВА',
    'ПАО '),
    payer_of_the_railway_tariff LIKE '%ОТКРЫТОЕ АКЦИОНЕРНОЕ ОБЩЕСТВО%',
    replaceAll(payer_of_the_railway_tariff,
    'ОТКРЫТОЕ АКЦИОНЕРНОЕ ОБЩЕСТВО',
    'ОАО '),
    payer_of_the_railway_tariff LIKE '%ЗАКРЫТОЕ АКЦИОНЕРНОЕ ОБЩЕСТВО%',
    replaceAll(payer_of_the_railway_tariff,
    'ЗАКРЫТОЕ АКЦИОНЕРНОЕ ОБЩЕСТВО',
    'ЗАО '),
    payer_of_the_railway_tariff LIKE '%ТОВАРИЩЕНСТВО С ОГРАНИЧЕННОЙ ОТВЕТСТВЕННОСТЬЮ%',
    replaceAll(payer_of_the_railway_tariff,
    'ТОВАРИЩЕНСТВО С ОГРАНИЧЕННОЙ ОТВЕТСТВЕННОСТЬЮ',
    'ТОО '),
    payer_of_the_railway_tariff LIKE '%АКЦИОНЕРНОЕ ОБЩЕСТВО%',
    replaceAll(payer_of_the_railway_tariff,
    'АКЦИОНЕРНОЕ ОБЩЕСТВО',
    'АО '),
    payer_of_the_railway_tariff LIKE '%АКЦИОНЕРНОГО ОБЩЕСТВА%',
    replaceAll(payer_of_the_railway_tariff,
    'АКЦИОНЕРНОГО ОБЩЕСТВА',
    'АО '),
    payer_of_the_railway_tariff LIKE '%ФЕДЕРАЛЬНОЕ АГЕНТСТВО%',
    replaceAll(payer_of_the_railway_tariff,
    'ФЕДЕРАЛЬНОЕ АГЕНТСТВО',
    'ФА '),
    payer_of_the_railway_tariff LIKE '%ООО%',
    replaceAll(payer_of_the_railway_tariff,
    'ООО',
    'ООО '),
    payer_of_the_railway_tariff LIKE '%ОАО%',
    replaceAll(payer_of_the_railway_tariff,
    'ОАО',
    'ОАО '),
    payer_of_the_railway_tariff LIKE '%ПАО%',
    replaceAll(payer_of_the_railway_tariff,
    'ПАО',
    'ПАО '),
    payer_of_the_railway_tariff LIKE '%ЗАО%',
    replaceAll(payer_of_the_railway_tariff,
    'ЗАО',
    'ЗАО '),
    payer_of_the_railway_tariff LIKE '%НАО%',
    replaceAll(payer_of_the_railway_tariff,
    'НАО',
    'НАО '),
    payer_of_the_railway_tariff
);
