CREATE OR REPLACE FUNCTION replace_company_name AS (payer_of_the_railway_tariff) ->
multiIf(
    payer_of_the_railway_tariff LIKE '%АКЦИОНЕРНАЯ КОМПАНИЯ%',
    replaceAll(payer_of_the_railway_tariff,
    'АКЦИОНЕРНАЯ КОМПАНИЯ',
    'АК'),
    payer_of_the_railway_tariff LIKE '%ОАО ТРАНСКОНТЕЙНЕР%',
    replaceAll(payer_of_the_railway_tariff,
    'ОАО ТРАНСКОНТЕЙНЕР',
    'ПАО ТРАНСКОНТЕЙНЕР'),
    payer_of_the_railway_tariff LIKE '%ОООАЗИЯВНЕШТРАНС%',
    replaceAll(payer_of_the_railway_tariff,
    'ОООАЗИЯВНЕШТРАНС',
    'ООО АЗИЯВНЕШТРАНС'),
    payer_of_the_railway_tariff LIKE '%АО МОНДИ СЫКТЫВКАРСКИЙ ЛПК%',
    replaceAll(payer_of_the_railway_tariff,
    'АО МОНДИ СЫКТЫВКАРСКИЙ ЛПК',
    'АО МОНДИ СЛПК'),
    payer_of_the_railway_tariff LIKE '%ГОРНО-ОБОГАТИТЕЛЬНЫЙ КОМБИНАТ%',
    replaceAll(payer_of_the_railway_tariff,
    'ГОРНО-ОБОГАТИТЕЛЬНЫЙ КОМБИНАТ',
    'ГОК'),
    payer_of_the_railway_tariff LIKE '%ООО ФЕСКО ИНТЕГРИРОВАННЫЙ ТРАНСПОРТ%',
    replaceAll(payer_of_the_railway_tariff,
    'ООО ФЕСКО ИНТЕГРИРОВАННЫЙ ТРАНСПОРТ',
    'ФИТ'),
    payer_of_the_railway_tariff LIKE '%АО ОБЪЕДИНЕННАЯ ТРАНСПОРТНО-ЛОГИСТИЧЕСКАЯ КОМПАНИЯ%',
    replaceAll(payer_of_the_railway_tariff,
    'АО ОБЪЕДИНЕННАЯ ТРАНСПОРТНО-ЛОГИСТИЧЕСКАЯ КОМПАНИЯ',
    'ОТЛК'),
    payer_of_the_railway_tariff
);
