CREATE TABLE IF NOT EXISTS rzhd.rzhd_novorossiysk
(
    `wagon_number` Nullable(String),
    `document_no` Nullable(String),
    `departure_date` Date,
    `type_of_transportation` Nullable(String),
    `wagon_subgenus` Nullable(String),
    `cargo_code_of_the_etsng` Nullable(String),
    `name_of_cargo` Nullable(String),
    `state_of_departure` Nullable(String),
    `departure_region` Nullable(String),
    `departure_road` Nullable(String),
    `sign_of_departure_station_of_the_rf` Nullable(String),
    `shipper_according_to_egrpo` Nullable(String),
    `shipper_okpo` Nullable(String),
    `type_of_special_container` Nullable(String),
    `departure_station_code_of_rf` Nullable(String),
    `state_of_destination` Nullable(String),
    `destination_region` Nullable(String),
    `destination_road` Nullable(String),
    `rf_destination_station` Nullable(String),
    `consignee_according_to_egrpo` Nullable(String),
    `consignee_okpo` Nullable(String),
    `wagon_operator` Nullable(String),
    `destination_station_code_of_rf` Nullable(String),
    `wagon_owner_according_to_egrpo` Nullable(String),
    `leaseholder` Nullable(String),
    `payer_of_the_railway_tariff` Nullable(String),
    `weight` Nullable(Decimal128(19)),
    `carriage_fee` Nullable(Bigint),
    `cargo_class` Nullable(Bigint),
    `cis_departure_station` Nullable(String),
    `cis_destination_station` Nullable(String),
    `container_no` Nullable(String),
    `dispatch_category` Nullable(String),
    `container_tonnage` Nullable(String),
    `wagon_model` Nullable(String),
    `estimated_date_of_arrival` Nullable(Date),
    `arrival_date` Nullable(Date),
    `wagon_kilometers` Nullable(Bigint),
    `date_of_disbursement` Nullable(Date),
    `distance_zone_of_grouping_by_mileage` Nullable(String),
    `departure_road_cis` Nullable(String),
    `destination_road_cis` Nullable(String),
    `shipper_by_puzt` Nullable(String),
    `consignee_by_puzt` Nullable(String),
    `departure_station_code_of_cis` Nullable(String),
    `destination_station_code_of_cis` Nullable(String),
    `departure_station_of_the_rf` Nullable(String),
    `original_file_name` Nullable(String),
    `original_file_parsed_on` Nullable(String),
    `original_file_index` Nullable(Bigint)
)
ENGINE = MergeTree()
ORDER BY departure_date;
