CREATE OR REPLACE VIEW merchants.automation_shippers_consignees_view
AS
SELECT
    destination_station,
    rs.station_unified AS destination_station_unified,
    if(seller_priority IS NOT NULL, seller_priority, seller) AS seller,
    if(seller_priority_taxpayer_id IS NOT NULL, seller_priority_taxpayer_id, seller_taxpayer_id) AS seller_taxpayer_id,
    if(seller_priority_unified IS NOT NULL, seller_priority_unified, seller_unified) AS seller_unified,
    if(buyer_priority IS NOT NULL, buyer_priority, buyer) AS buyer,
    if(buyer_priority_taxpayer_id IS NOT NULL, buyer_priority_taxpayer_id, buyer_taxpayer_id) AS buyer_taxpayer_id,
    if(buyer_priority_unified IS NOT NULL, buyer_priority_unified, buyer_unified) AS buyer_unified,
    replaceRegexpAll(input_data, concat('^[', regexpQuoteMeta('(.rar)'), ']+|[', regexpQuoteMeta('(.rar)'), ']+$'), '') AS daytime,
    multiIf(daytime ILIKE '%Январь%',
         '01',
         daytime ILIKE '%Февраль%',
         '02',
         daytime ILIKE '%Март%',
         '03',
         daytime ILIKE '%Апрель%',
         '04',
         daytime ILIKE '%Май%',
         '05',
         daytime ILIKE '%Июнь%',
         '06',
         daytime ILIKE '%Июль%',
         '07',
         daytime ILIKE '%Август%',
         '08',
         daytime ILIKE '%Сентябрь%',
         '09',
         daytime ILIKE '%Октябрь%',
         '10',
         daytime ILIKE '%Ноябрь%',
         '11',
         daytime ILIKE '%Декабрь%',
         '12',
         'Ошибка'
    ) AS month,
    multiIf(daytime ILIKE '%2020%',
         '2020',
         daytime ILIKE '%2021%',
         '2021',
         daytime ILIKE '%2022%',
         '2022',
         daytime ILIKE '%2023%',
         '2023',
         daytime ILIKE '%2024%',
         '2024',
         daytime ILIKE '%2025%',
         '2025',
         daytime ILIKE '%2026%',
         '2026',
         'Ошибка'
   ) AS year,
    count(original_file_name) AS count_container
FROM merchants.automation_shippers_consignees
LEFT JOIN merchants.reference_stations rs ON destination_station = rs.station
GROUP BY
    destination_station,
    destination_station_unified,
    seller,
    seller_taxpayer_id,
    seller_unified,
    buyer,
    buyer_taxpayer_id,
    buyer_unified,
    daytime;