CREATE OR REPLACE VIEW rzhd.rzhd_novorossiysk_view
AS
    SELECT
        wagon_number AS wagon_number,
        document_no AS document_no,
        departure_date AS departure_date,
        quantity_of_containers AS quantity_of_containers,
        container_no AS container_no,
        departure_month AS departure_month,
        departure_year AS departure_year,
        type_of_transportation AS type_of_transportation,
        wagon_subgenus AS wagon_subgenus,
        cargo_code_of_the_etsng AS cargo_code_of_the_etsng,
        name_of_cargo AS name_of_cargo,
        state_of_departure AS state_of_departure,
        departure_region AS departure_region,
        departure_road AS departure_road,
        sign_of_departure_station_of_the_rf AS sign_of_departure_station_of_the_rf,
        shipper_according_to_egrpo AS shipper_according_to_egrpo,
        shipper_by_puzt AS shipper_by_puzt,
        common_shipper AS common_shipper,
        shipper_okpo AS shipper_okpo,
        type_of_special_container AS type_of_special_container,
        container_type_unified AS container_type_unified,
        departure_station_code_of_rf AS departure_station_code_of_rf,
        state_of_destination AS state_of_destination,
        destination_region AS destination_region,
        destination_road AS destination_road,
        rf_destination_station AS rf_destination_station,
        consignee_according_to_egrpo AS consignee_according_to_egrpo,
        consignee_by_puzt AS consignee_by_puzt,
        common_consignee AS common_consignee,
        consignee_okpo AS consignee_okpo,
        wagon_operator AS wagon_operator,
        destination_station_code_of_rf AS destination_station_code_of_rf,
        wagon_owner_according_to_egrpo AS wagon_owner_according_to_egrpo,
        leaseholder AS leaseholder,
        payer_of_the_railway_tariff AS payer_of_the_railway_tariff,
        weight AS weight,
        carriage_fee AS carriage_fee,
        cargo_class AS cargo_class,
        cis_departure_station AS cis_departure_station,
        cis_destination_station AS cis_destination_station,
        dispatch_category AS dispatch_category,
        container_tonnage AS container_tonnage,
        container_tonnage_unified AS container_tonnage_unified,
        multiIf
        (
            quantity_of_containers <= 0,
            0,
            container_tonnage_unified is null,
            null,
            teu
        ) AS teu,
        wagon_model AS wagon_model,
        estimated_date_of_arrival AS estimated_date_of_arrival,
        arrival_date AS arrival_date,
        wagon_kilometers AS wagon_kilometers,
        date_of_disbursement AS date_of_disbursement,
        distance_zone_of_grouping_by_mileage AS distance_zone_of_grouping_by_mileage,
        departure_road_cis AS departure_road_cis,
        destination_road_cis AS destination_road_cis,
        departure_station_code_of_cis AS departure_station_code_of_cis,
        destination_station_code_of_cis AS destination_station_code_of_cis,
        departure_station_of_the_rf AS departure_station_of_the_rf,
        original_file_name AS original_file_name,
        original_file_parsed_on AS original_file_parsed_on,
        original_file_index AS original_file_index,
        group_wagon_doc_date AS group_wagon_doc_date
    FROM rzhd.rzhd_novorossiysk_container_0_view
        UNION ALL
    SELECT
        wagon_number AS wagon_number,
        document_no AS document_no,
        departure_date AS departure_date,
        quantity_of_containers AS quantity_of_containers,
        container_no AS container_no,
        departure_month AS departure_month,
        departure_year AS departure_year,
        type_of_transportation AS type_of_transportation,
        wagon_subgenus AS wagon_subgenus,
        cargo_code_of_the_etsng AS cargo_code_of_the_etsng,
        name_of_cargo AS name_of_cargo,
        state_of_departure AS state_of_departure,
        departure_region AS departure_region,
        departure_road AS departure_road,
        sign_of_departure_station_of_the_rf AS sign_of_departure_station_of_the_rf,
        shipper_according_to_egrpo AS shipper_according_to_egrpo,
        shipper_by_puzt AS shipper_by_puzt,
        common_shipper AS common_shipper,
        shipper_okpo AS shipper_okpo,
        type_of_special_container AS type_of_special_container,
        container_type_unified AS container_type_unified,
        departure_station_code_of_rf AS departure_station_code_of_rf,
        state_of_destination AS state_of_destination,
        destination_region AS destination_region,
        destination_road AS destination_road,
        rf_destination_station AS rf_destination_station,
        consignee_according_to_egrpo AS consignee_according_to_egrpo,
        consignee_by_puzt AS consignee_by_puzt,
        common_consignee AS common_consignee,
        consignee_okpo AS consignee_okpo,
        wagon_operator AS wagon_operator,
        destination_station_code_of_rf AS destination_station_code_of_rf,
        wagon_owner_according_to_egrpo AS wagon_owner_according_to_egrpo,
        leaseholder AS leaseholder,
        payer_of_the_railway_tariff AS payer_of_the_railway_tariff,
        weight AS weight,
        carriage_fee AS carriage_fee,
        cargo_class AS cargo_class,
        cis_departure_station AS cis_departure_station,
        cis_destination_station AS cis_destination_station,
        dispatch_category AS dispatch_category,
        container_tonnage AS container_tonnage,
        container_tonnage_unified AS container_tonnage_unified,
        multiIf
        (
            quantity_of_containers <= 0,
            0,
            container_tonnage_unified is null,
            null,
            teu
        ) AS teu,
        wagon_model AS wagon_model,
        estimated_date_of_arrival AS estimated_date_of_arrival,
        arrival_date AS arrival_date,
        wagon_kilometers AS wagon_kilometers,
        date_of_disbursement AS date_of_disbursement,
        distance_zone_of_grouping_by_mileage AS distance_zone_of_grouping_by_mileage,
        departure_road_cis AS departure_road_cis,
        destination_road_cis AS destination_road_cis,
        departure_station_code_of_cis AS departure_station_code_of_cis,
        destination_station_code_of_cis AS destination_station_code_of_cis,
        departure_station_of_the_rf AS departure_station_of_the_rf,
        original_file_name AS original_file_name,
        original_file_parsed_on AS original_file_parsed_on,
        original_file_index AS original_file_index,
        group_wagon_doc_date AS group_wagon_doc_date
    FROM rzhd.rzhd_novorossiysk_container_view;