CREATE OR REPLACE VIEW rzhd.rzhd_petersburg_view
AS SELECT
    rzhd_petersburg.wagon_number AS wagon_number,
    rzhd_petersburg.container_no AS container_no,
    rzhd_petersburg.document_no AS document_no,
    rzhd_petersburg.code_of_conditional_type_of_wagon AS code_of_conditional_type_of_wagon,
    rzhd_petersburg.departure_road AS departure_road,
    rzhd_petersburg.name_of_cargo AS name_of_cargo,
    rzhd_petersburg.wagon_type AS wagon_type,
    rzhd_petersburg.wagon_type_descriptions AS wagon_type_descriptions,
    rzhd_petersburg.departure_station_of_the_rf AS departure_station_of_the_rf,
    rzhd_petersburg.administration_of_the_cis_departure_station AS administration_of_the_cis_departure_station,
    rzhd_petersburg.administration_of_the_cis_destination_station AS administration_of_the_cis_destination_station,
    rzhd_petersburg.leaseholder AS leaseholder,
    rzhd_petersburg.exceptional_rate_code AS exceptional_rate_code,
    rzhd_petersburg.departure_date AS departure_date,
    toMonth(departure_date) AS departure_month,
    toYear(departure_date) AS departure_year,
    rzhd_petersburg.departure_day_report AS departure_day_report,
    rzhd_petersburg.number_of_cargo_acceptances_for_transportation AS number_of_cargo_acceptances_for_transportation,
    rzhd_petersburg.destination_road AS destination_road,
    rzhd_petersburg.type_of_transportation AS type_of_transportation,
    rzhd_petersburg.type_of_communication_between_countries_by_rail AS type_of_communication_between_countries_by_rail,
    if(dispatch_category is not null, dispatch_category, 'нет данных') AS dispatch_category,
    rzhd_petersburg.quantity_of_containers AS quantity_of_containers,
    rzhd_petersburg.quantity_of_wagons AS quantity_of_wagons,
    rzhd_petersburg.wagon_ownership_sign AS wagon_ownership_sign,
    rzhd_petersburg.currency_code AS currency_code,
    rzhd_petersburg.cargo_according_to_the_harmonized_nomenclature_of_goods_gng AS cargo_according_to_the_harmonized_nomenclature_of_goods_gng,
    rzhd_petersburg.cargo_code_according_to_the_harmonized_nomenclature_of_goods_gng AS cargo_code_according_to_the_harmonized_nomenclature_of_goods_gng,
    rzhd_petersburg.state_of_departure AS state_of_departure,
    rzhd_petersburg.state_of_destination AS state_of_destination,
    rzhd_petersburg.sign_of_the_state_of_destination AS sign_of_the_state_of_destination,
    rzhd_petersburg.sign_of_the_state_of_departure AS sign_of_the_state_of_departure,
    rzhd_petersburg.load_capacity AS load_capacity,
    rzhd_petersburg.group_of_cargo_according_to_the_operational_nomenclature AS group_of_cargo_according_to_the_operational_nomenclature,
    rzhd_petersburg.group_of_cargo_according_to_co22 AS group_of_cargo_according_to_co22,
    rzhd_petersburg.group_of_cargo_according_to_go7 AS group_of_cargo_according_to_go7,
    rzhd_petersburg.sub_group_of_cargo AS sub_group_of_cargo,
    rzhd_petersburg.cargo_group AS cargo_group,
    rzhd_petersburg.cargo_code_of_the_etsng AS cargo_code_of_the_etsng,
    replace_organization_form(payer_of_the_railway_tariff) AS payer_of_the_railway_tariff,
    rzhd_petersburg.cargo_class AS cargo_class,
    rzhd_petersburg.departure_station_code_of_rf AS departure_station_code_of_rf,
    rzhd_petersburg.destination_station_code_of_rf AS destination_station_code_of_rf,
    rzhd_petersburg.departure_station_code_of_cis AS departure_station_code_of_cis,
    rzhd_petersburg.destination_station_code_of_cis AS destination_station_code_of_cis,
    rzhd_petersburg.the_owner_of_the_wagon_according_to_the_internal_directory AS the_owner_of_the_wagon_according_to_the_internal_directory,
    rzhd_petersburg.wagon_operator AS wagon_operator,
    rzhd_petersburg.sign_of_a_lease AS sign_of_a_lease,
    rzhd_petersburg.month_of_acceptance_of_cargo_for_transportation AS month_of_acceptance_of_cargo_for_transportation,
    rzhd_petersburg.year_of_acceptance_of_cargo_for_transportation AS year_of_acceptance_of_cargo_for_transportation,
    rzhd_petersburg.departure_region AS departure_region,
    rzhd_petersburg.destination_region AS destination_region,
    rzhd_petersburg.carriage_fee AS carriage_fee,
    rzhd_petersburg.wagon_owner_according_to_egrpo AS wagon_owner_according_to_egrpo,
    rzhd_petersburg.shipper_okpo AS shipper_okpo,
    rzhd_petersburg.shipper_according_to_egrpo AS shipper_according_to_egrpo,
    rzhd_petersburg.shipper_by_puzt AS shipper_by_puzt,
    swap_values(shipper_by_puzt, shipper_according_to_egrpo, 'неизвестен') AS common_shipper,
    rzhd_petersburg.distance_zone_of_grouping_by_mileage AS distance_zone_of_grouping_by_mileage,
    rzhd_petersburg.consignee_according_to_egrpo AS consignee_according_to_egrpo,
    rzhd_petersburg.consignee_by_puzt AS consignee_by_puzt,
    swap_values(consignee_by_puzt, consignee_according_to_egrpo, 'неизвестен') AS common_consignee,
    rzhd_petersburg.consignee_okpo AS consignee_okpo,
    rzhd_petersburg.container_prefix AS container_prefix,
    rzhd_petersburg.wagon_subgenus AS wagon_subgenus,
    rzhd_petersburg.sign_of_the_place_of_settlement AS sign_of_the_place_of_settlement,
    rzhd_petersburg.sign_of_non_credited_cargo_at_border_crossings AS sign_of_non_credited_cargo_at_border_crossings,
    rzhd_petersburg.sign_of_the_principal AS sign_of_the_principal,
    rzhd_petersburg.container_tonnage AS container_tonnage,
    rt.container_tonnage_unified AS container_tonnage_unified,
    multiIf
    (
        quantity_of_containers = 0 or quantity_of_containers = -1,
        0,
        rt.container_tonnage_unified is null,
        null,
        floor(divide(rt.container_tonnage_unified, 20), 1)
    ) AS teu,
    rzhd_petersburg.subject_of_departure_of_the_rf AS subject_of_departure_of_the_rf,
    rzhd_petersburg.destination_subject_of_the_rf AS destination_subject_of_the_rf,
    rzhd_petersburg.type_of_wagon_according_to_co29 AS type_of_wagon_according_to_co29,
    rzhd_petersburg.wagon_subtype_according_to_co28 AS wagon_subtype_according_to_co28,
    rzhd_petersburg.discount_amount AS discount_amount,
    rzhd_petersburg.state_owner_of_the_wagon AS state_owner_of_the_wagon,
    rzhd_petersburg.sign_of_the_border_crossing_of_the_destination_of_the_rf AS sign_of_the_border_crossing_of_the_destination_of_the_rf,
    rzhd_petersburg.sign_of_the_border_crossing_of_the_destination_of_the_cis AS sign_of_the_border_crossing_of_the_destination_of_the_cis,
    rzhd_petersburg.sign_of_the_border_crossing_of_the_departure_of_the_cis AS sign_of_the_border_crossing_of_the_departure_of_the_cis,
    rzhd_petersburg.sign_of_the_border_crossing_of_the_departure_of_the_rf AS sign_of_the_border_crossing_of_the_departure_of_the_rf,
    rzhd_petersburg.rf_destination_station AS rf_destination_station,
    rzhd_petersburg.sign_of_destination_station_of_the_rf AS sign_of_destination_station_of_the_rf,
    rzhd_petersburg.cis_departure_station AS cis_departure_station,
    rzhd_petersburg.cis_destination_station AS cis_destination_station,
    rzhd_petersburg.sign_of_destination_station_of_the_cis AS sign_of_destination_station_of_the_cis,
    rzhd_petersburg.sign_of_the_departure_station_of_the_cis AS sign_of_the_departure_station_of_the_cis,
    rzhd_petersburg.sign_of_departure_station_of_the_rf AS sign_of_departure_station_of_the_rf,
    rzhd_petersburg.conditional_wagon_type AS conditional_wagon_type,
    rzhd_petersburg.park_type AS park_type,
    rzhd_petersburg.cargo_turnover AS cargo_turnover,
    rzhd_petersburg.tariff_sign AS tariff_sign,
    rzhd_petersburg.transportation_volume_tons AS transportation_volume_tons,
    rzhd_petersburg.tara_weight_of_an_empty_wagon AS tara_weight_of_an_empty_wagon,
    rzhd_petersburg.type_of_accounting AS type_of_accounting,
    rzhd_petersburg.wagon_kilometers AS wagon_kilometers,
    rzhd_petersburg.sign_of_the_exclusive_tariff AS sign_of_the_exclusive_tariff,
    rzhd_petersburg.name_of_cargo_etsng AS name_of_cargo_etsng,
    rzhd_petersburg.type_of_special_container AS type_of_special_container,
    rct.container_type_unified AS container_type_unified,
    rzhd_petersburg.group_of_cargo_according_to_go6 AS group_of_cargo_according_to_go6,
    rzhd_petersburg.cargo_group_according_to_etsng AS cargo_group_according_to_etsng,
    rzhd_petersburg.group_of_cargo_co21 AS group_of_cargo_co21,
    rzhd_petersburg.wagon_subtype_according_to_co29 AS wagon_subtype_according_to_co29,
    rzhd_petersburg.original_file_name AS original_file_name,
    rzhd_petersburg.original_file_parsed_on AS original_file_parsed_on,
    rzhd_petersburg.original_file_index AS original_file_index
   FROM rzhd.rzhd_petersburg
     LEFT JOIN rzhd.reference_tonnage AS rt ON rzhd_petersburg.container_tonnage = rt.container_tonnage
     LEFT JOIN rzhd.reference_container_type AS rct ON rzhd_petersburg.type_of_special_container = rct.type_of_special_container;