CREATE TABLE IF NOT EXISTS crm.teams
    (
    `odata.etag` Nullable(String),
    `_queueid_value` Nullable(String),
    `organizationid` Nullable(String),
    `_businessunitid_value` Nullable(String),
    `_administratorid_value` Nullable(String),
    `systemmanaged` Nullable(Bool),
    `isdefault` Nullable(Bool),
    `teamtype` Nullable(Integer),
    `createdon` Nullable(Date),
    `description` Nullable(String),
    `versionnumber` Integer,
    `modifiedon` Nullable(Date),
    `name` Nullable(String),
    `teamid` Nullable(String),
    `ownerid` Nullable(String),
    `_transactioncurrencyid_value` Nullable(String),
    `yominame` Nullable(String),
    `_teamtemplateid_value` Nullable(String),
    `_modifiedonbehalfby_value` Nullable(String),
    `traversedpath` Nullable(String),
    `exchangerate` Nullable(Decimal128(19)),
    `importsequencenumber` Nullable(Integer),
    `_createdby_value` Nullable(String),
    `emailaddress` Nullable(String),
    `processid` Nullable(String),
    `_regardingobjectid_value` Nullable(String),
    `stageid` Nullable(String),
    `overriddencreatedon` Nullable(String),
    `_modifiedby_value` Nullable(String),
    `_createdonbehalfby_value` Nullable(String),
    )
ENGINE = MergeTree()
ORDER BY versionnumber;